spring:
  application:
    name: coffee_pp
  liquibase:
    enabled: false
    change-log: liquibase/master.xml
  datasource:
    url: jdbc:postgresql://localhost:5434/coffee_db
    username: postgres
    password: postgres
    generate-unique-name: false
  security:
    user:
      name: user
      password: password


server:
  port: 8080